#spring.application.name=cartify
#
#spring.h2.console.enabled=true
#spring.datasource.url=jdbc:h2:mem:test
#


spring:
  application:
    name: cartify
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:test