#spring.application.name=cartify
#
#spring.h2.console.enabled=true
#spring.datasource.url=jdbc:h2:mem:test
#


spring:
  application:
    name: cartify
  datasource:
    url: jdbc:postgresql://localhost:5432/cartifyDB
    username: cartify
    password: cartify
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate.jdbc.time_zone: Asia/Kolkata

#  h2:
#    console:
#      enabled: true
#  datasource:
#    url: jdbc:h2:mem:test

management:
  endpoints:
    web:
      exposure:
#        include: '*'
        include: beans, health
  endpoint:
    health:
      show-details: always
#      show-details: never
#      show-details: when-authorized
#    shutdown:
#      enabled: true
  info:
    env:
      enabled: true
info:
  app:
    name: CartifyEcomm
    description: Ecomm App
    version: 1.1

#server:
#  shutdown: graceful


logging:
  level:
    org.hibernate: DEBUG
    org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator: TRACE

